# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 400_000_000
max_iters: -1
eval_interval: -1
save_interval: -1
seed: 0

# policy_checkpoint_path: /home/hesicheng/OmniDrones/policy_checkpoints/large.pt

viewer:
  resolution: [960, 720]
  eye: [6, 0., 4.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity: marl-drones
  project: omnidrones
  mode: online # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: PingPongRelay
  - algo: mappo
  - _self_
